// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// discover
void discover(std::string name, unsigned time);
RcppExport SEXP _Rzeroconf_discover(SEXP nameSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< unsigned >::type time(timeSEXP);
    discover(name, time);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rzeroconf_discover", (DL_FUNC) &_Rzeroconf_discover, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rzeroconf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
