# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
browse <- function(type = "_http._tcp", domain = "local", wait = 500L) {
    .Call(`_Rzeroconf_browse`, type, domain, wait)
}

