# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
discover <- function(name = "_http._tcp", time = 5000L) {
    invisible(.Call(`_Rzeroconf_discover`, name, time))
}

