# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
browse_service <- function(type, domain = "local") {
    .Call(`_Rzeroconf_browse_service`, type, domain)
}

get_browser_results <- function(b) {
    .Call(`_Rzeroconf_get_browser_results`, b)
}

#' @export
avahi_browse_service <- function(type, domain = "local") {
    .Call(`_Rzeroconf_avahi_browse_service`, type, domain)
}

#' @export
avahi_get_results <- function(ptr) {
    .Call(`_Rzeroconf_avahi_get_results`, ptr)
}

#' @export
avahi_browse_domain <- function(domain = "local") {
    .Call(`_Rzeroconf_avahi_browse_domain`, domain)
}

#' @export
register_service <- function(name, type, domain, port, txt_record) {
    .Call(`_Rzeroconf_register_service`, name, type, domain, port, txt_record)
}

